# Kingdom center coordinates in SVG space (843.75 x 568.5)
# Generated by generate_kingdom_overlays.py

const KINGDOM_CENTERS = {
    "Vylfod_Dominion": Vector2(346.88, 284.34),
    "Rabaric_Republic": Vector2(206.19, 208.77),
    "Kingdom_of_El_Ruhn": Vector2(215.42, 146.32),
    "Kelsin_Federation": Vector2(351.50, 131.44),
    "Divine_Empire_of_Gosain": Vector2(277.22, 197.82),
    "Yozuan_Desert": Vector2(169.44, 155.78),
}

const SVG_SIZE = Vector2(843.75, 568.5)

# Convert SVG coordinates to screen coordinates
static func svg_to_screen(svg_pos: Vector2, container_size: Vector2) -> Vector2:
    return Vector2(
        (svg_pos.x / SVG_SIZE.x) * container_size.x,
        (svg_pos.y / SVG_SIZE.y) * container_size.y
    )
